[book]
language = "en"
multilingual = false
src = "src"
title = "foo book"

[preprocessor.fishextract]
# there is mermaid support via js via the mermaid preprocessort
renderer = ["tectonic", "markdown", "latex"]
fragment_path = "fragments/fishextract"
assets = "assets/fishextract"

[preprocessor.mermaid]
renderer = ["html"]
command = "mdbook-mermaid"

[preprocessor.scientific]
# there is mathjax support via js in the html renderer
renderer = ["tectonic", "markdown", "latex"]
fragment_path = "fragments/scientific"
assets = "assets/scientific"

# additional-js = [ "mermaid.min.js", "mermaid-init.js" ]

[output.tectonic]
latex = true    # default = true
markdown = true # default = false
pdf = true      # default = false
assets = ["assets/scientific", "assets/fishextract"]
