[book]
title = "foo test book"
authors = ["Bernhard Schuster <bernhard@ahoi.io>"]
multilingual = false
src = "src"

[preprocessor.fishextract]
renderer = ["tectonic", "latex"]
assets = "assets/fishextract"
fragment_path = "fragments"


[preprocessor.scientific]
renderer = ["tectonic", "latex", "html"]
assets = "assets/scientific"
fragment_path = "fragments"

[output.tectonic]
latex = true    # default = true
markdown = true # default = false
pdf = true      # default = false
